version: '3.8' #This version is depend on Docker Enginer version Ref : https://docs.docker.com/compose/compose-file/compose-versioning/
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8989:3000
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=webapp_db
      - MYSQL_ROOT_PASSWORD=pa55w0rd
    volumes:
      - db_store:/var/lib/mysql
volumes:
  db_store:
      


    